services:
  jellynews:
    hostname: "jellynews.docker"
    build: .
    restart: unless-stopped
    environment:
      - JELLYFIN_SERVER_URL=https://public.jellyfin.com
      - FB_GRAPH_API_TOKEN=0123456789abcdefghi
    ports:
      - 8008:8080  # Bot port
      - 5021:5021

